//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.07 at 01:11:19 PM CST 
//


package com.itender.ms.platform.country.entity;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="projectOpenBidListCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="openBidRecordCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bidSectionCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="23"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isUnion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *               &lt;pattern value="[0|1]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unionCodeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unionCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unionName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unionMemberBasicInfoVersion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bidderCodeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bidderCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bidderName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bidderBasicInfoVersion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{14}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="duration">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="bidAmount">
 *               &lt;simpleType>
 *                 &lt;restriction base="{}limit-decimal">
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *             &lt;element name="currencyCode">
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;pattern value="[0-9]{3}"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *             &lt;element name="priceUnit">
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;pattern value="[1|2]"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;element name="otherBidPrice">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;minLength value="1"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="pmName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pmCodeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pmCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="otherOpenBidContent">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="version">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{14}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isOpen">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0|1|2]|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="openType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0|1|2]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="examinerName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="examinerCodeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="examinerCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="verifyTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{14}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectOpenBidListCode",
    "openBidRecordCode",
    "bidSectionCode",
    "isUnion",
    "unionCodeType",
    "unionCode",
    "unionName",
    "unionMemberBasicInfoVersion",
    "bidderCodeType",
    "bidderCode",
    "bidderName",
    "bidderBasicInfoVersion",
    "duration",
    "bidAmount",
    "currencyCode",
    "priceUnit",
    "otherBidPrice",
    "pmName",
    "pmCodeType",
    "pmCode",
    "otherOpenBidContent",
    "version",
    "isOpen",
    "openType",
    "examinerName",
    "examinerCodeType",
    "examinerCode",
    "verifyTime"
})
@XmlRootElement(name = "projectOpenBidList")
public class ProjectOpenBidList {

    @XmlElement(required = true)
    protected String projectOpenBidListCode;
    @XmlElement(required = true)
    protected String openBidRecordCode;
    @XmlElement(required = true)
    protected String bidSectionCode;
    @XmlElement(required = true)
    protected String isUnion;
    @XmlElement(required = true)
    protected String unionCodeType;
    @XmlElement(required = true)
    protected String unionCode;
    @XmlElement(required = true)
    protected String unionName;
    @XmlElement(required = true)
    protected String unionMemberBasicInfoVersion;
    @XmlElement(required = true)
    protected String bidderCodeType;
    @XmlElement(required = true)
    protected String bidderCode;
    @XmlElement(required = true)
    protected String bidderName;
    @XmlElement(required = true)
    protected String bidderBasicInfoVersion;
    @XmlElement(required = true)
    protected String duration;
    protected BigDecimal bidAmount;
    protected String currencyCode;
    protected String priceUnit;
    protected String otherBidPrice;
    @XmlElement(required = true)
    protected String pmName;
    @XmlElement(required = true)
    protected String pmCodeType;
    @XmlElement(required = true)
    protected String pmCode;
    @XmlElement(required = true)
    protected String otherOpenBidContent;
    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected String isOpen;
    @XmlElement(required = true)
    protected String openType;
    @XmlElement(required = true)
    protected String examinerName;
    @XmlElement(required = true)
    protected String examinerCodeType;
    @XmlElement(required = true)
    protected String examinerCode;
    @XmlElement(required = true)
    protected String verifyTime;

    /**
     * Gets the value of the projectOpenBidListCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectOpenBidListCode() {
        return projectOpenBidListCode;
    }

    /**
     * Sets the value of the projectOpenBidListCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectOpenBidListCode(String value) {
        this.projectOpenBidListCode = value;
    }

    /**
     * Gets the value of the openBidRecordCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenBidRecordCode() {
        return openBidRecordCode;
    }

    /**
     * Sets the value of the openBidRecordCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenBidRecordCode(String value) {
        this.openBidRecordCode = value;
    }

    /**
     * Gets the value of the bidSectionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBidSectionCode() {
        return bidSectionCode;
    }

    /**
     * Sets the value of the bidSectionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBidSectionCode(String value) {
        this.bidSectionCode = value;
    }

    /**
     * Gets the value of the isUnion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsUnion() {
        return isUnion;
    }

    /**
     * Sets the value of the isUnion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsUnion(String value) {
        this.isUnion = value;
    }

    /**
     * Gets the value of the unionCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnionCodeType() {
        return unionCodeType;
    }

    /**
     * Sets the value of the unionCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnionCodeType(String value) {
        this.unionCodeType = value;
    }

    /**
     * Gets the value of the unionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnionCode() {
        return unionCode;
    }

    /**
     * Sets the value of the unionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnionCode(String value) {
        this.unionCode = value;
    }

    /**
     * Gets the value of the unionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnionName() {
        return unionName;
    }

    /**
     * Sets the value of the unionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnionName(String value) {
        this.unionName = value;
    }

    /**
     * Gets the value of the unionMemberBasicInfoVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnionMemberBasicInfoVersion() {
        return unionMemberBasicInfoVersion;
    }

    /**
     * Sets the value of the unionMemberBasicInfoVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnionMemberBasicInfoVersion(String value) {
        this.unionMemberBasicInfoVersion = value;
    }

    /**
     * Gets the value of the bidderCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBidderCodeType() {
        return bidderCodeType;
    }

    /**
     * Sets the value of the bidderCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBidderCodeType(String value) {
        this.bidderCodeType = value;
    }

    /**
     * Gets the value of the bidderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBidderCode() {
        return bidderCode;
    }

    /**
     * Sets the value of the bidderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBidderCode(String value) {
        this.bidderCode = value;
    }

    /**
     * Gets the value of the bidderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBidderName() {
        return bidderName;
    }

    /**
     * Sets the value of the bidderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBidderName(String value) {
        this.bidderName = value;
    }

    /**
     * Gets the value of the bidderBasicInfoVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBidderBasicInfoVersion() {
        return bidderBasicInfoVersion;
    }

    /**
     * Sets the value of the bidderBasicInfoVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBidderBasicInfoVersion(String value) {
        this.bidderBasicInfoVersion = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the bidAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBidAmount() {
        return bidAmount;
    }

    /**
     * Sets the value of the bidAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBidAmount(BigDecimal value) {
        this.bidAmount = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the priceUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceUnit() {
        return priceUnit;
    }

    /**
     * Sets the value of the priceUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceUnit(String value) {
        this.priceUnit = value;
    }

    /**
     * Gets the value of the otherBidPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherBidPrice() {
        return otherBidPrice;
    }

    /**
     * Sets the value of the otherBidPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherBidPrice(String value) {
        this.otherBidPrice = value;
    }

    /**
     * Gets the value of the pmName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmName() {
        return pmName;
    }

    /**
     * Sets the value of the pmName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmName(String value) {
        this.pmName = value;
    }

    /**
     * Gets the value of the pmCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmCodeType() {
        return pmCodeType;
    }

    /**
     * Sets the value of the pmCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmCodeType(String value) {
        this.pmCodeType = value;
    }

    /**
     * Gets the value of the pmCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmCode() {
        return pmCode;
    }

    /**
     * Sets the value of the pmCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmCode(String value) {
        this.pmCode = value;
    }

    /**
     * Gets the value of the otherOpenBidContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherOpenBidContent() {
        return otherOpenBidContent;
    }

    /**
     * Sets the value of the otherOpenBidContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherOpenBidContent(String value) {
        this.otherOpenBidContent = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the isOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsOpen() {
        return isOpen;
    }

    /**
     * Sets the value of the isOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsOpen(String value) {
        this.isOpen = value;
    }

    /**
     * Gets the value of the openType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenType() {
        return openType;
    }

    /**
     * Sets the value of the openType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenType(String value) {
        this.openType = value;
    }

    /**
     * Gets the value of the examinerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExaminerName() {
        return examinerName;
    }

    /**
     * Sets the value of the examinerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExaminerName(String value) {
        this.examinerName = value;
    }

    /**
     * Gets the value of the examinerCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExaminerCodeType() {
        return examinerCodeType;
    }

    /**
     * Sets the value of the examinerCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExaminerCodeType(String value) {
        this.examinerCodeType = value;
    }

    /**
     * Gets the value of the examinerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExaminerCode() {
        return examinerCode;
    }

    /**
     * Sets the value of the examinerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExaminerCode(String value) {
        this.examinerCode = value;
    }

    /**
     * Gets the value of the verifyTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerifyTime() {
        return verifyTime;
    }

    /**
     * Sets the value of the verifyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerifyTime(String value) {
        this.verifyTime = value;
    }

}
