//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.07 at 01:12:46 PM CST 
//


package com.itender.ms.platform.country.entity;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="projectCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="17"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tenderProjectCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tradePlatfTenderProjectCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tenderProjectName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tenderProjectClassifyCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="regionCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{6}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tenderContent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tendererCodeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tendererCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tendererName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tenderAgencyCodeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tenderAgencyCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tenderAgencyName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tendererAgencyBasicInfoVersion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{14}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tenderMode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[1|2|9]|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tenderOrganizeForm">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[1|2|3|9]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="createTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{14}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="superviseDeptCodeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="superviseDeptCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="superviseDeptName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveDeptCodeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveDeptCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveDeptName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="platformCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9A-Z]{11}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pubServicePlatCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9A-Z]{11}|[0-9A-Z]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="infoReporterName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="infoReporterCodeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="infoReporterCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="examinerName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="examinerCodeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{2}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="examinerCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="attachmentCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="version">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{14}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isOpen">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0|1|2]|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="openType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0|1|2]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="verifyTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{14}|[0-9]{0}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectCode",
    "tenderProjectCode",
    "tradePlatfTenderProjectCode",
    "tenderProjectName",
    "tenderProjectClassifyCode",
    "regionCode",
    "tenderContent",
    "tendererCodeType",
    "tendererCode",
    "tendererName",
    "tenderAgencyCodeType",
    "tenderAgencyCode",
    "tenderAgencyName",
    "tendererAgencyBasicInfoVersion",
    "tenderMode",
    "tenderOrganizeForm",
    "createTime",
    "superviseDeptCodeType",
    "superviseDeptCode",
    "superviseDeptName",
    "approveDeptCodeType",
    "approveDeptCode",
    "approveDeptName",
    "platformCode",
    "pubServicePlatCode",
    "infoReporterName",
    "infoReporterCodeType",
    "infoReporterCode",
    "examinerName",
    "examinerCodeType",
    "examinerCode",
    "attachmentCode",
    "version",
    "isOpen",
    "openType",
    "verifyTime"
})
/**
 * 招标项目
 *
 * @author Frank
 *
 */
@XmlRootElement(name = "tenderProject")
public class TenderProject {
	public static final String TENDERPROJECT="TENDERPROJECT";
    @XmlElement(required = true)
    protected String projectCode;
    @XmlElement(required = true)
    protected String tenderProjectCode;
    @XmlElement(required = true)
    protected String tradePlatfTenderProjectCode;
    @XmlElement(required = true)
    protected String tenderProjectName;
    @XmlElement(required = true)
    protected String tenderProjectClassifyCode;
    @XmlElement(required = true)
    protected String regionCode;
    @XmlElement(required = true)
    protected String tenderContent;
    @XmlElement(required = true)
    protected String tendererCodeType;
    @XmlElement(required = true)
    protected String tendererCode;
    @XmlElement(required = true)
    protected String tendererName;
    @XmlElement(required = true)
    protected String tenderAgencyCodeType;
    @XmlElement(required = true)
    protected String tenderAgencyCode;
    @XmlElement(required = true)
    protected String tenderAgencyName;
    @XmlElement(required = true)
    protected String tendererAgencyBasicInfoVersion;
    @XmlElement(required = true)
    protected String tenderMode;
    @XmlElement(required = true)
    protected String tenderOrganizeForm;
    @XmlElement(required = true)
    protected String createTime;
    @XmlElement(required = true)
    protected String superviseDeptCodeType;
    @XmlElement(required = true)
    protected String superviseDeptCode;
    @XmlElement(required = true)
    protected String superviseDeptName;
    @XmlElement(required = true)
    protected String approveDeptCodeType;
    @XmlElement(required = true)
    protected String approveDeptCode;
    @XmlElement(required = true)
    protected String approveDeptName;
    @XmlElement(required = true)
    protected String platformCode;
    @XmlElement(required = true)
    protected String pubServicePlatCode;
    @XmlElement(required = true)
    protected String infoReporterName;
    @XmlElement(required = true)
    protected String infoReporterCodeType;
    @XmlElement(required = true)
    protected String infoReporterCode;
    @XmlElement(required = true)
    protected String examinerName;
    @XmlElement(required = true)
    protected String examinerCodeType;
    @XmlElement(required = true)
    protected String examinerCode;
    @XmlElement(required = true)
    protected String attachmentCode;
    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected String isOpen;
    @XmlElement(required = true)
    protected String openType;
    @XmlElement(required = true)
    protected String verifyTime;

    /**
     * Gets the value of the projectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * Sets the value of the projectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectCode(String value) {
        this.projectCode = value;
    }

    /**
     * Gets the value of the tenderProjectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderProjectCode() {
        return tenderProjectCode;
    }

    /**
     * Sets the value of the tenderProjectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderProjectCode(String value) {
        this.tenderProjectCode = value;
    }

    /**
     * Gets the value of the tradePlatfTenderProjectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradePlatfTenderProjectCode() {
        return tradePlatfTenderProjectCode;
    }

    /**
     * Sets the value of the tradePlatfTenderProjectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradePlatfTenderProjectCode(String value) {
        this.tradePlatfTenderProjectCode = value;
    }

    /**
     * Gets the value of the tenderProjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderProjectName() {
        return tenderProjectName;
    }

    /**
     * Sets the value of the tenderProjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderProjectName(String value) {
        this.tenderProjectName = value;
    }

    /**
     * Gets the value of the tenderProjectClassifyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderProjectClassifyCode() {
        return tenderProjectClassifyCode;
    }

    /**
     * Sets the value of the tenderProjectClassifyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderProjectClassifyCode(String value) {
        this.tenderProjectClassifyCode = value;
    }

    /**
     * Gets the value of the regionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * Sets the value of the regionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionCode(String value) {
        this.regionCode = value;
    }

    /**
     * Gets the value of the tenderContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderContent() {
        return tenderContent;
    }

    /**
     * Sets the value of the tenderContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderContent(String value) {
        this.tenderContent = value;
    }

    /**
     * Gets the value of the tendererCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTendererCodeType() {
        return tendererCodeType;
    }

    /**
     * Sets the value of the tendererCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTendererCodeType(String value) {
        this.tendererCodeType = value;
    }

    /**
     * Gets the value of the tendererCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTendererCode() {
        return tendererCode;
    }

    /**
     * Sets the value of the tendererCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTendererCode(String value) {
        this.tendererCode = value;
    }

    /**
     * Gets the value of the tendererName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTendererName() {
        return tendererName;
    }

    /**
     * Sets the value of the tendererName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTendererName(String value) {
        this.tendererName = value;
    }

    /**
     * Gets the value of the tenderAgencyCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderAgencyCodeType() {
        return tenderAgencyCodeType;
    }

    /**
     * Sets the value of the tenderAgencyCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderAgencyCodeType(String value) {
        this.tenderAgencyCodeType = value;
    }

    /**
     * Gets the value of the tenderAgencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderAgencyCode() {
        return tenderAgencyCode;
    }

    /**
     * Sets the value of the tenderAgencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderAgencyCode(String value) {
        this.tenderAgencyCode = value;
    }

    /**
     * Gets the value of the tenderAgencyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderAgencyName() {
        return tenderAgencyName;
    }

    /**
     * Sets the value of the tenderAgencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderAgencyName(String value) {
        this.tenderAgencyName = value;
    }

    /**
     * Gets the value of the tendererAgencyBasicInfoVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTendererAgencyBasicInfoVersion() {
        return tendererAgencyBasicInfoVersion;
    }

    /**
     * Sets the value of the tendererAgencyBasicInfoVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTendererAgencyBasicInfoVersion(String value) {
        this.tendererAgencyBasicInfoVersion = value;
    }

    /**
     * Gets the value of the tenderMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderMode() {
        return tenderMode;
    }

    /**
     * Sets the value of the tenderMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderMode(String value) {
        this.tenderMode = value;
    }

    /**
     * Gets the value of the tenderOrganizeForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderOrganizeForm() {
        return tenderOrganizeForm;
    }

    /**
     * Sets the value of the tenderOrganizeForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderOrganizeForm(String value) {
        this.tenderOrganizeForm = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateTime(String value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the superviseDeptCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperviseDeptCodeType() {
        return superviseDeptCodeType;
    }

    /**
     * Sets the value of the superviseDeptCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperviseDeptCodeType(String value) {
        this.superviseDeptCodeType = value;
    }

    /**
     * Gets the value of the superviseDeptCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperviseDeptCode() {
        return superviseDeptCode;
    }

    /**
     * Sets the value of the superviseDeptCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperviseDeptCode(String value) {
        this.superviseDeptCode = value;
    }

    /**
     * Gets the value of the superviseDeptName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperviseDeptName() {
        return superviseDeptName;
    }

    /**
     * Sets the value of the superviseDeptName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperviseDeptName(String value) {
        this.superviseDeptName = value;
    }

    /**
     * Gets the value of the approveDeptCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproveDeptCodeType() {
        return approveDeptCodeType;
    }

    /**
     * Sets the value of the approveDeptCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproveDeptCodeType(String value) {
        this.approveDeptCodeType = value;
    }

    /**
     * Gets the value of the approveDeptCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproveDeptCode() {
        return approveDeptCode;
    }

    /**
     * Sets the value of the approveDeptCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproveDeptCode(String value) {
        this.approveDeptCode = value;
    }

    /**
     * Gets the value of the approveDeptName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproveDeptName() {
        return approveDeptName;
    }

    /**
     * Sets the value of the approveDeptName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproveDeptName(String value) {
        this.approveDeptName = value;
    }

    /**
     * Gets the value of the platformCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformCode() {
        return platformCode;
    }

    /**
     * Sets the value of the platformCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformCode(String value) {
        this.platformCode = value;
    }

    /**
     * Gets the value of the pubServicePlatCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubServicePlatCode() {
        return pubServicePlatCode;
    }

    /**
     * Sets the value of the pubServicePlatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubServicePlatCode(String value) {
        this.pubServicePlatCode = value;
    }

    /**
     * Gets the value of the infoReporterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfoReporterName() {
        return infoReporterName;
    }

    /**
     * Sets the value of the infoReporterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfoReporterName(String value) {
        this.infoReporterName = value;
    }

    /**
     * Gets the value of the infoReporterCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfoReporterCodeType() {
        return infoReporterCodeType;
    }

    /**
     * Sets the value of the infoReporterCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfoReporterCodeType(String value) {
        this.infoReporterCodeType = value;
    }

    /**
     * Gets the value of the infoReporterCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfoReporterCode() {
        return infoReporterCode;
    }

    /**
     * Sets the value of the infoReporterCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfoReporterCode(String value) {
        this.infoReporterCode = value;
    }

    /**
     * Gets the value of the examinerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExaminerName() {
        return examinerName;
    }

    /**
     * Sets the value of the examinerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExaminerName(String value) {
        this.examinerName = value;
    }

    /**
     * Gets the value of the examinerCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExaminerCodeType() {
        return examinerCodeType;
    }

    /**
     * Sets the value of the examinerCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExaminerCodeType(String value) {
        this.examinerCodeType = value;
    }

    /**
     * Gets the value of the examinerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExaminerCode() {
        return examinerCode;
    }

    /**
     * Sets the value of the examinerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExaminerCode(String value) {
        this.examinerCode = value;
    }

    /**
     * Gets the value of the attachmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachmentCode() {
        return attachmentCode;
    }

    /**
     * Sets the value of the attachmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachmentCode(String value) {
        this.attachmentCode = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the isOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsOpen() {
        return isOpen;
    }

    /**
     * Sets the value of the isOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsOpen(String value) {
        this.isOpen = value;
    }

    /**
     * Gets the value of the openType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenType() {
        return openType;
    }

    /**
     * Sets the value of the openType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenType(String value) {
        this.openType = value;
    }

    /**
     * Gets the value of the verifyTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerifyTime() {
        return verifyTime;
    }

    /**
     * Sets the value of the verifyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerifyTime(String value) {
        this.verifyTime = value;
    }

	@Override
	public String toString() {
		return "TenderProject [projectCode=" + projectCode
				+ ", tenderProjectCode=" + tenderProjectCode
				+ ", tradePlatfTenderProjectCode="
				+ tradePlatfTenderProjectCode + ", tenderProjectName="
				+ tenderProjectName + ", tenderProjectClassifyCode="
				+ tenderProjectClassifyCode + ", regionCode=" + regionCode
				+ ", tenderContent=" + tenderContent + ", tendererCodeType="
				+ tendererCodeType + ", tendererCode=" + tendererCode
				+ ", tendererName=" + tendererName + ", tenderAgencyCodeType="
				+ tenderAgencyCodeType + ", tenderAgencyCode="
				+ tenderAgencyCode + ", tenderAgencyName=" + tenderAgencyName
				+ ", tendererAgencyBasicInfoVersion="
				+ tendererAgencyBasicInfoVersion + ", tenderMode=" + tenderMode
				+ ", tenderOrganizeForm=" + tenderOrganizeForm
				+ ", createTime=" + createTime + ", superviseDeptCodeType="
				+ superviseDeptCodeType + ", superviseDeptCode="
				+ superviseDeptCode + ", superviseDeptName="
				+ superviseDeptName + ", approveDeptCodeType="
				+ approveDeptCodeType + ", approveDeptCode=" + approveDeptCode
				+ ", approveDeptName=" + approveDeptName + ", platformCode="
				+ platformCode + ", pubServicePlatCode=" + pubServicePlatCode
				+ ", infoReporterName=" + infoReporterName
				+ ", infoReporterCodeType=" + infoReporterCodeType
				+ ", infoReporterCode=" + infoReporterCode + ", examinerName="
				+ examinerName + ", examinerCodeType=" + examinerCodeType
				+ ", examinerCode=" + examinerCode + ", attachmentCode="
				+ attachmentCode + ", version=" + version + ", isOpen="
				+ isOpen + ", openType=" + openType + ", verifyTime="
				+ verifyTime + "]";
	}
    
    
    

}
