######################
#Log4j2配置
logging:
  config: classpath:config/log4j2.xml
#Spring配置
spring:
    ## 多环境配置
    profiles:
        active: staging

 #设置文件上大小
    http:
        multipart:
          max-file-size: 1024MB
          max-request-size: 1024MB
          enabled: true
          resolve-lazily: true
    #数据库配置
    datasource:
        name: vote
        url: jdbc:mysql://${db.ip}:3306/${db.name}?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8
        username: ${db.username}
        password: ${db.password}

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        initialSize: 10
        maxActive: 200
        maxWait: 30000
        minIdle: 10
        maxOpenPreparedStatements: 20
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true
        minEvictableIdleTimeMillis: 30000
        keepAlive: true
        dbcp2:
          pool-prepared-statements: true
        tomcat:
          time-between-eviction-runs-millis: 30000

    jpa:
      database: MYSQL
      hibernate:
        ddl-auto: update
      show-sql: true



mapper:
#    mappers:
#        - CustomMapper
    not-empty: false
#    identity: select lower(sys_guid()) from dual
    identity: select uuid()
    ORDER: BEFORE

pagehelper:
    helperDialect: mysql
#    helperDialect: oracle
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


sys:
  version: "@project.version@"



debug: false

mybatis-plus:
  global-config:
    id-type: 3
    refresh-mapper: true
    field-strategy: 2
    db-column-underline: true
    logic-delete-value: -1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  type-aliases-package: com.vote.ms.entity
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      call-setters-on-nulls: true
  mapper-locations: classpath:mapper/**/*.xml

