##Staging环境
spring:
    profiles: pro


#服务端口
server:
  port: 9090


#数据库IP
db:
  ip: 127.0.0.1
  name: itender_supervise
  username: root
  password: Ycp7WyjzNA

    #http对接地址
httpRequest:
   domain:  http://47.94.142.243:9090
   socket:  47.94.142.243


