##Staging环境
spring:
    profiles: staging


#服务端口
server:
  port: 9090


#数据库IP
db:
  ip: 39.106.4.105
  name: orcl
  username: tender_57
  password: live_tendre12


httpRequest:
    domain:  http://192.168.99.19:8080
    host:  http://39.107.127.11:9090
    socket:  0.0.0.0

