######################
#Log4j2配置
logging:
  config: classpath:config/log4j2.xml
#Spring配置
spring:
    ## 多环境配置
    profiles:
        active: dev

 #设置文件上大小
    http:
        multipart:
          max-file-size: 1024MB
          max-request-size: 1024MB
          enabled: true
          resolve-lazily: true
    #数据库配置
    datasource:
        name: itender
        url: jdbc:oracle:thin:@${db.ip}:1521:${db.name}
#        url: jdbc:oracle:thin:@${db.ip}:1521:${db.name}
        username: ${db.username}
        password: ${db.password}

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
#        driver-class-name: oracle.jdbc.driver.OracleDriver
        filters: stat
        initialSize: 1
        maxActive: 20
        maxWait: 30000
        minIdle: 1
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true
        timeBetweenEvictionRunsMillis: 30000
        minEvictableIdleTimeMillis: 30000
        keepAlive: true





    activiti:
      database-schema-update: true
      db-identity-used: false
      job-executor-activate: true
      async-executor-activate: false
    mvc:
      view:
        prefix: WEB-INF/pages/
        suffix: .jsp




#Mybatis配置
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: tk.mapper.model


mapper:
#    mappers:
#        - CustomMapper
    not-empty: false
#    identity: select lower(sys_guid()) from dual
    identity: select lower(sys_guid()) from dual
    ORDER: BEFORE

pagehelper:
    helperDialect: oracle
#    helperDialect: oracle
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


sys:
  version: "@project.version@"



debug: false

