##Staging环境
spring:
    profiles: dev


#服务端口
server:
  port: 9090


#数据库IP
db:
  ip: 39.107.127.11
  name: itender_supervise
  username: root
  password: Ycp7WyjzNA

    #http对接地址
httpRequest:
   domain:  http://47.94.241.88:80
   host:  http://192.168.99.133:9090
   socket:  0.0.0.0


