##Staging环境
spring:
    profiles: staging


#服务端口
server:
  port: 9090


#数据库IP
db:
  ip: 47.94.142.243 #pro 47.94.142.243 ,stage 47.94.241.88
  name: itender_supervise
  username: root  #pro root , stage  dev
  password: Ycp7WyjzNA


httpRequest:
    domain: http://192.168.99.19:8080
    socket:  0.0.0.0

