##Staging环境
spring:
    profiles: chanpin


#服务端口
server:
  port: 9900


#数据库IP
db:
  ip: 172.17.119.78 #39.107.127.11
  name: bank_guarantee
  username: root
  password: Ycp7WyjzNA


httpRequest:
    domain:  http://192.168.99.19:8080
    host:  http://39.107.127.11:9090
    socket:  0.0.0.0

