##Staging环境
spring:
    profiles: dev


#服务端口
server:
  port: 9090


#数据库IP
#数据库IP
db:
  ip: 39.106.4.105
  name: orcl
  username: tender_test
  password: test_df278f

    #http对接地址
httpRequest:
   domain:  http://10.0.0.145:8080
   host:  http://192.168.99.133:9090
   socket:  0.0.0.0


