//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 03:16:03 PM CST 
//


package com.itender.ms.platform.shanxi;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 *
 * @author Frank
 *	招标文件/招标文件澄清与修改
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectcode",//项目编号
    "tenderprojectcode",//招标项目编号
    "bidsectioncode",//标段（包）编码
    "unifieddealcodes",//统一交易标识码
    "docno",//文件编号
    "bidqualification",//投标资格
    "biddocreferendtime",//投标文件递交截止时间
    "validperiod",//投标有效期
    "biddocrefermethod",//投标文件递交方法
    "marginpaytype",//投标保证金缴纳方式
    "marginamount",//投标保证金金额（单位：万元）
    "controlprice",//控制价（最高限价）（如有）
    "evaluatingmethod",//评标办法
    "bidopentime",//开标时间
    "bidopenplace",//开标地点
    "bidopentype",//开标方式
    "qualtype",//资格审查方式
    "clarifytime",//答疑澄清时间
    "ispostpone",//是否延期
    "postopentime",//延期后开标时间
    "postopenaddress",//延期后开标地点
    "clarifycontent",//对文件澄清与修改的主要内容
    "submittime",//递交时间
    "platformcode",//交易系统标识码
    "pubserviceplatcode",//公共服务平台标识码
    "datatimestamp",//数据时间戳
    "docname",//文件名称
    "url"//文件源URL
})
@XmlRootElement(name = "GCJS_TENDER_DOC")
public class GCJSTENDERDOC {
	public static final String GCJS_TENDER_DOC="GCJS_TENDER_DOC";
    @XmlElement(name = "PROJECT_CODE", required = true)
    protected String projectcode;
    @XmlElement(name = "TENDER_PROJECT_CODE", required = true)
    protected String tenderprojectcode;
    @XmlElement(name = "BID_SECTION_CODE", required = true)
    protected String bidsectioncode;
    @XmlElement(name = "UNIFIED_DEAL_CODES", required = true)
    protected String unifieddealcodes;
    @XmlElement(name = "DOC_NO")
    protected String docno;
    @XmlElement(name = "BID_QUALIFICATION", required = true)
    protected String bidqualification;
    @XmlElement(name = "BID_DOC_REFER_END_TIME", required = true)
    protected String biddocreferendtime;
    @XmlElement(name = "VALID_PERIOD", required = true)
    protected String validperiod;
    @XmlElement(name = "BID_DOC_REFER_METHOD", required = true)
    protected String biddocrefermethod;
    @XmlElement(name = "MARGIN_PAY_TYPE", required = true)
    protected String marginpaytype;
    @XmlElement(name = "MARGIN_AMOUNT", required = true)
    protected String marginamount;
    @XmlElement(name = "CONTROL_PRICE", required = false)
    protected String controlprice;
    @XmlElement(name = "EVALUATING_METHOD", required = true)
    protected String evaluatingmethod;
    @XmlElement(name = "BID_OPEN_TIME", required = true)
    protected String bidopentime;
    @XmlElement(name = "BID_OPEN_PLACE", required = true)
    protected String bidopenplace;
    @XmlElement(name = "BID_OPEN_TYPE", required = true)
    protected String bidopentype;
    @XmlElement(name = "QUAL_TYPE", required = true)
    protected String qualtype;
    @XmlElement(name = "CLARIFY_TIME")
    protected String clarifytime;
    @XmlElement(name = "IS_POSTPONE", required = true)
    protected String ispostpone;
    @XmlElement(name = "POST_OPEN_TIME", required = true)
    protected String postopentime;
    @XmlElement(name = "POST_OPEN_ADDRESS", required = true)
    protected String postopenaddress;
    @XmlElement(name = "CLARIFY_CONTENT", required = true)
    protected String clarifycontent;
    @XmlElement(name = "SUBMIT_TIME", required = true)
    protected String submittime;
    @XmlElement(name = "PLATFORM_CODE", required = true)
    protected String platformcode;
    @XmlElement(name = "PUB_SERVICE_PLAT_CODE", required = true)
    protected String pubserviceplatcode;
    @XmlElement(name = "DATA_TIMESTAMP", required = true)
    protected String datatimestamp;
    @XmlElement(name = "DOC_NAME", required = true)
    protected String docname;
    @XmlElement(name = "URL", required = true)
    protected String url;

    /**
     * Gets the value of the projectcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROJECTCODE() {
        return projectcode;
    }

    /**
     * Sets the value of the projectcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROJECTCODE(String value) {
        this.projectcode = value;
    }

    /**
     * Gets the value of the tenderprojectcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERPROJECTCODE() {
        return tenderprojectcode;
    }

    /**
     * Sets the value of the tenderprojectcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERPROJECTCODE(String value) {
        this.tenderprojectcode = value;
    }

    /**
     * Gets the value of the bidsectioncode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDSECTIONCODE() {
        return bidsectioncode;
    }

    /**
     * Sets the value of the bidsectioncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDSECTIONCODE(String value) {
        this.bidsectioncode = value;
    }

    /**
     * Gets the value of the unifieddealcodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNIFIEDDEALCODES() {
        return unifieddealcodes;
    }

    /**
     * Sets the value of the unifieddealcodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNIFIEDDEALCODES(String value) {
        this.unifieddealcodes = value;
    }

    /**
     * Gets the value of the docno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCNO() {
        return docno;
    }

    /**
     * Sets the value of the docno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCNO(String value) {
        this.docno = value;
    }

    /**
     * Gets the value of the bidqualification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDQUALIFICATION() {
        return bidqualification;
    }

    /**
     * Sets the value of the bidqualification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDQUALIFICATION(String value) {
        this.bidqualification = value;
    }

    /**
     * Gets the value of the biddocreferendtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDDOCREFERENDTIME() {
        return biddocreferendtime;
    }

    /**
     * Sets the value of the biddocreferendtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDDOCREFERENDTIME(String value) {
        this.biddocreferendtime = value;
    }

    /**
     * Gets the value of the validperiod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDPERIOD() {
        return validperiod;
    }

    /**
     * Sets the value of the validperiod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDPERIOD(String value) {
        this.validperiod = value;
    }

    /**
     * Gets the value of the biddocrefermethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDDOCREFERMETHOD() {
        return biddocrefermethod;
    }

    /**
     * Sets the value of the biddocrefermethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDDOCREFERMETHOD(String value) {
        this.biddocrefermethod = value;
    }

    /**
     * Gets the value of the marginpaytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARGINPAYTYPE() {
        return marginpaytype;
    }

    /**
     * Sets the value of the marginpaytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARGINPAYTYPE(String value) {
        this.marginpaytype = value;
    }

    /**
     * Gets the value of the marginamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public String getMARGINAMOUNT() {
        return marginamount;
    }

    /**
     * Sets the value of the marginamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMARGINAMOUNT(String value) {
        this.marginamount = value;
    }

    /**
     * Gets the value of the controlprice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTROLPRICE() {
        return controlprice;
    }

    /**
     * Sets the value of the controlprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTROLPRICE(String value) {
        this.controlprice = value;
    }

    /**
     * Gets the value of the evaluatingmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVALUATINGMETHOD() {
        return evaluatingmethod;
    }

    /**
     * Sets the value of the evaluatingmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVALUATINGMETHOD(String value) {
        this.evaluatingmethod = value;
    }

    /**
     * Gets the value of the bidopentime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDOPENTIME() {
        return bidopentime;
    }

    /**
     * Sets the value of the bidopentime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDOPENTIME(String value) {
        this.bidopentime = value;
    }

    /**
     * Gets the value of the bidopenplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDOPENPLACE() {
        return bidopenplace;
    }

    /**
     * Sets the value of the bidopenplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDOPENPLACE(String value) {
        this.bidopenplace = value;
    }

    /**
     * Gets the value of the bidopentype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDOPENTYPE() {
        return bidopentype;
    }

    /**
     * Sets the value of the bidopentype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDOPENTYPE(String value) {
        this.bidopentype = value;
    }

    /**
     * Gets the value of the qualtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUALTYPE() {
        return qualtype;
    }

    /**
     * Sets the value of the qualtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUALTYPE(String value) {
        this.qualtype = value;
    }

    /**
     * Gets the value of the clarifytime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLARIFYTIME() {
        return clarifytime;
    }

    /**
     * Sets the value of the clarifytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLARIFYTIME(String value) {
        this.clarifytime = value;
    }

    /**
     * Gets the value of the ispostpone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPOSTPONE() {
        return ispostpone;
    }

    /**
     * Sets the value of the ispostpone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPOSTPONE(String value) {
        this.ispostpone = value;
    }

    /**
     * Gets the value of the postopentime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTOPENTIME() {
        return postopentime;
    }

    /**
     * Sets the value of the postopentime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTOPENTIME(String value) {
        this.postopentime = value;
    }

    /**
     * Gets the value of the postopenaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTOPENADDRESS() {
        return postopenaddress;
    }

    /**
     * Sets the value of the postopenaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTOPENADDRESS(String value) {
        this.postopenaddress = value;
    }

    /**
     * Gets the value of the clarifycontent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLARIFYCONTENT() {
        return clarifycontent;
    }

    /**
     * Sets the value of the clarifycontent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLARIFYCONTENT(String value) {
        this.clarifycontent = value;
    }

    /**
     * Gets the value of the submittime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBMITTIME() {
        return submittime;
    }

    /**
     * Sets the value of the submittime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBMITTIME(String value) {
        this.submittime = value;
    }

    /**
     * Gets the value of the platformcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLATFORMCODE() {
        return platformcode;
    }

    /**
     * Sets the value of the platformcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLATFORMCODE(String value) {
        this.platformcode = value;
    }

    /**
     * Gets the value of the pubserviceplatcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUBSERVICEPLATCODE() {
        return pubserviceplatcode;
    }

    /**
     * Sets the value of the pubserviceplatcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUBSERVICEPLATCODE(String value) {
        this.pubserviceplatcode = value;
    }

    /**
     * Gets the value of the datatimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATATIMESTAMP() {
        return datatimestamp;
    }

    /**
     * Sets the value of the datatimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATATIMESTAMP(String value) {
        this.datatimestamp = value;
    }

    /**
     * Gets the value of the docname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCNAME() {
        return docname;
    }

    /**
     * Sets the value of the docname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCNAME(String value) {
        this.docname = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

	@Override
	public String toString() {
		return "GCJSTENDERDOC [projectcode=" + projectcode
				+ ", tenderprojectcode=" + tenderprojectcode
				+ ", bidsectioncode=" + bidsectioncode + ", unifieddealcodes="
				+ unifieddealcodes + ", docno=" + docno + ", bidqualification="
				+ bidqualification + ", biddocreferendtime="
				+ biddocreferendtime + ", validperiod=" + validperiod
				+ ", biddocrefermethod=" + biddocrefermethod
				+ ", marginpaytype=" + marginpaytype + ", marginamount="
				+ marginamount + ", controlprice=" + controlprice
				+ ", evaluatingmethod=" + evaluatingmethod + ", bidopentime="
				+ bidopentime + ", bidopenplace=" + bidopenplace
				+ ", bidopentype=" + bidopentype + ", qualtype=" + qualtype
				+ ", clarifytime=" + clarifytime + ", ispostpone=" + ispostpone
				+ ", postopentime=" + postopentime + ", postopenaddress="
				+ postopenaddress + ", clarifycontent=" + clarifycontent
				+ ", submittime=" + submittime + ", platformcode="
				+ platformcode + ", pubserviceplatcode=" + pubserviceplatcode
				+ ", datatimestamp=" + datatimestamp + ", docname=" + docname
				+ ", url=" + url + "]";
	}
    
}
