//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 03:13:17 PM CST 
//


package com.itender.ms.platform.shanxi;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectcode",
    "bidsectioncode",
    "unifieddealcode",
    "tenderername",
    "tendercode",
    "biddername",
    "biddercode",
    "contractprice",
    "settleprice",
    "contractcontent",
    "limitetime",
    "qualityrequire",
    "performchangecontent",
    "finishtime",
    "actuallyperiod",
    "performinfo",
    "submittime",
    "contractsigntime",
    "platformcode",
    "pubserviceplatcode",
    "datatimestamp",
    "contractname"
})
/**
 * 合同和履约
 * @author Developer
 *
 */
@XmlRootElement(name = "GCJS_CONTRACT_PERFORMANCE")
public class GCJSCONTRACTPERFORMANCE {

    @XmlElement(name = "PROJECT_CODE", required = true)
    protected String projectcode;//项目编号
    @XmlElement(name = "BID_SECTION_CODE", required = true)
    protected String bidsectioncode;//标段(包)编号
    @XmlElement(name = "UNIFIED_DEAL_CODE", required = true)
    protected String unifieddealcode;//相关统一交易标识码
    @XmlElement(name = "TENDERER_NAME", required = true)
    protected String tenderername;//招标人名称
    @XmlElement(name = "TENDER_CODE", required = true)
    protected String tendercode;//招标人代码
    @XmlElement(name = "BIDDER_NAME", required = true)
    protected String biddername;//中标人名称
    @XmlElement(name = "BIDDER_CODE", required = true)
    protected String biddercode;//中标人代码
    @XmlElement(name = "CONTRACT_PRICE", required = true)
    protected String contractprice;//合同金额(单位：万元)
    @XmlElement(name = "SETTLE_PRICE")
    protected String settleprice;//合同结算金额(单位：万元)
    @XmlElement(name = "CONTRACT_CONTENT", required = true)
    protected String contractcontent;//合同主要内容
    @XmlElement(name = "LIMITE_TIME")
    protected String limitetime;//合同期限
    @XmlElement(name = "QUALITY_REQUIRE")
    protected String qualityrequire;//质量要求
    @XmlElement(name = "PERFORM_CHANGE_CONTENT")
    protected String performchangecontent;//履约变更内容
    @XmlElement(name = "FINISH_TIME", required = true)
    protected String finishtime;//合同完成时间
    @XmlElement(name = "ACTUALLY_PERIOD")
    protected String actuallyperiod;//实际履约期限
    @XmlElement(name = "PERFORM_INFO")
    protected String performinfo;//履约信息
    @XmlElement(name = "SUBMIT_TIME")
    protected String submittime;//递交时间
    @XmlElement(name = "CONTRACT_SIGN_TIME", required = true)
    protected String contractsigntime;//合同签署时间
    @XmlElement(name = "PLATFORM_CODE", required = true)
    protected String platformcode;//交易系统标识码
    @XmlElement(name = "PUB_SERVICE_PLAT_CODE", required = true)
    protected String pubserviceplatcode;//公共服务平台标识码
    @XmlElement(name = "DATA_TIMESTAMP", required = true)
    protected String datatimestamp;//数据时间戳
    @XmlElement(name = "CONTRACT_NAME", required = true)
    protected String contractname;//合同名称

    /**
     * Gets the value of the projectcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROJECTCODE() {
        return projectcode;
    }

    /**
     * Sets the value of the projectcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROJECTCODE(String value) {
        this.projectcode = value;
    }

    /**
     * Gets the value of the bidsectioncode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDSECTIONCODE() {
        return bidsectioncode;
    }

    /**
     * Sets the value of the bidsectioncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDSECTIONCODE(String value) {
        this.bidsectioncode = value;
    }

    /**
     * Gets the value of the unifieddealcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNIFIEDDEALCODE() {
        return unifieddealcode;
    }

    /**
     * Sets the value of the unifieddealcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNIFIEDDEALCODE(String value) {
        this.unifieddealcode = value;
    }

    /**
     * Gets the value of the tenderername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERERNAME() {
        return tenderername;
    }

    /**
     * Sets the value of the tenderername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERERNAME(String value) {
        this.tenderername = value;
    }

    /**
     * Gets the value of the tendercode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERCODE() {
        return tendercode;
    }

    /**
     * Sets the value of the tendercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERCODE(String value) {
        this.tendercode = value;
    }

    /**
     * Gets the value of the biddername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDDERNAME() {
        return biddername;
    }

    /**
     * Sets the value of the biddername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDDERNAME(String value) {
        this.biddername = value;
    }

    /**
     * Gets the value of the biddercode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDDERCODE() {
        return biddercode;
    }

    /**
     * Sets the value of the biddercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDDERCODE(String value) {
        this.biddercode = value;
    }

    /**
     * Gets the value of the contractprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public String getCONTRACTPRICE() {
        return contractprice;
    }

    /**
     * Sets the value of the contractprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCONTRACTPRICE(String value) {
        this.contractprice = value;
    }

    /**
     * Gets the value of the settleprice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSETTLEPRICE() {
        return settleprice;
    }

    /**
     * Sets the value of the settleprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSETTLEPRICE(String value) {
        this.settleprice = value;
    }

    /**
     * Gets the value of the contractcontent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTRACTCONTENT() {
        return contractcontent;
    }

    /**
     * Sets the value of the contractcontent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTRACTCONTENT(String value) {
        this.contractcontent = value;
    }

    /**
     * Gets the value of the limitetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIMITETIME() {
        return limitetime;
    }

    /**
     * Sets the value of the limitetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIMITETIME(String value) {
        this.limitetime = value;
    }

    /**
     * Gets the value of the qualityrequire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUALITYREQUIRE() {
        return qualityrequire;
    }

    /**
     * Sets the value of the qualityrequire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUALITYREQUIRE(String value) {
        this.qualityrequire = value;
    }

    /**
     * Gets the value of the performchangecontent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPERFORMCHANGECONTENT() {
        return performchangecontent;
    }

    /**
     * Sets the value of the performchangecontent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPERFORMCHANGECONTENT(String value) {
        this.performchangecontent = value;
    }

    /**
     * Gets the value of the finishtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINISHTIME() {
        return finishtime;
    }

    /**
     * Sets the value of the finishtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINISHTIME(String value) {
        this.finishtime = value;
    }

    /**
     * Gets the value of the actuallyperiod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTUALLYPERIOD() {
        return actuallyperiod;
    }

    /**
     * Sets the value of the actuallyperiod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTUALLYPERIOD(String value) {
        this.actuallyperiod = value;
    }

    /**
     * Gets the value of the performinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPERFORMINFO() {
        return performinfo;
    }

    /**
     * Sets the value of the performinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPERFORMINFO(String value) {
        this.performinfo = value;
    }

    /**
     * Gets the value of the submittime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBMITTIME() {
        return submittime;
    }

    /**
     * Sets the value of the submittime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBMITTIME(String value) {
        this.submittime = value;
    }

    /**
     * Gets the value of the contractsigntime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTRACTSIGNTIME() {
        return contractsigntime;
    }

    /**
     * Sets the value of the contractsigntime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTRACTSIGNTIME(String value) {
        this.contractsigntime = value;
    }

    /**
     * Gets the value of the platformcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLATFORMCODE() {
        return platformcode;
    }

    /**
     * Sets the value of the platformcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLATFORMCODE(String value) {
        this.platformcode = value;
    }

    /**
     * Gets the value of the pubserviceplatcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUBSERVICEPLATCODE() {
        return pubserviceplatcode;
    }

    /**
     * Sets the value of the pubserviceplatcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUBSERVICEPLATCODE(String value) {
        this.pubserviceplatcode = value;
    }

    /**
     * Gets the value of the datatimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATATIMESTAMP() {
        return datatimestamp;
    }

    /**
     * Sets the value of the datatimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATATIMESTAMP(String value) {
        this.datatimestamp = value;
    }

    /**
     * Gets the value of the contractname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTRACTNAME() {
        return contractname;
    }

    /**
     * Sets the value of the contractname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTRACTNAME(String value) {
        this.contractname = value;
    }

}
