//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 03:16:16 PM CST 
//


package com.itender.ms.platform.shanxi;

import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectcode",
    "bidsectioncode",
    "unifieddealcode",
    "bidqualification",
    "biddername",
    "biddercodetype",
    "biddercode",
    "bidderrole",
    "tenderdocgettime",
    "tenderdocgetmethod",
    "biddocreferendtime",
    "biddocrefermethod",
    "bidinviteendtime",
    "bidinviteissuetime",
    "platformcode",
    "pubserviceplatcode",
    "datatimestamp"
})
/**
 * 投标邀请书
 * @author Developer
 *
 */
@XmlRootElement(name = "GCJS_TENDER_INVITATION")
public class GCJSTENDERINVITATION {

    @XmlElement(name = "PROJECT_CODE", required = true)
    protected String projectcode;//项目编号
    @XmlElement(name = "BID_SECTION_CODE", required = true)
    protected String bidsectioncode;//标段（包）编码
    @XmlElement(name = "UNIFIED_DEAL_CODE", required = true)
    protected String unifieddealcode;//统一交易标识码
    @XmlElement(name = "BID_QUALIFICATION")
    protected String bidqualification;//投标资格
    @XmlElement(name = "BIDDER_NAME", required = true)
    protected String biddername;//投标人名称
    @XmlElement(name = "BIDDER_CODE_TYPE", required = true)
    protected String biddercodetype;//投标人类别
    @XmlElement(name = "BIDDER_CODE", required = true)
    protected String biddercode;//投标人代码
    @XmlElement(name = "BIDDER_ROLE", required = true)
    protected String bidderrole;//投标人角色
    @XmlElement(name = "TENDER_DOC_GET_TIME", required = true)
    protected String tenderdocgettime;//招标文件/资格预审文件获取时间
    @XmlElement(name = "TENDER_DOC_GET_METHOD", required = true)
    protected String tenderdocgetmethod;//招标文件/资格预审文件获取方法
    @XmlElement(name = "BID_DOC_REFER_END_TIME", required = true)
    protected String biddocreferendtime;//投标文件/资审申请文件递交截止时间
    @XmlElement(name = "BID_DOC_REFER_METHOD", required = true)
    protected String biddocrefermethod;//投标文件/资审申请文件递交方法
    @XmlElement(name = "BID_INVITE_END_TIME")
    protected String bidinviteendtime;//回复截止时间
    @XmlElement(name = "BID_INVITE_ISSUE_TIME", required = true)
    protected String bidinviteissuetime;//投标邀请发出时间
    @XmlElement(name = "PLATFORM_CODE", required = true)
    protected String platformcode;//交易系统标识码
    @XmlElement(name = "PUB_SERVICE_PLAT_CODE", required = true)
    protected String pubserviceplatcode;//公共服务平台标识码
    @XmlElement(name = "DATA_TIMESTAMP", required = true)
    protected String datatimestamp;//数据时间戳

    /**
     * Gets the value of the projectcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROJECTCODE() {
        return projectcode;
    }

    /**
     * Sets the value of the projectcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROJECTCODE(String value) {
        this.projectcode = value;
    }

    /**
     * Gets the value of the bidsectioncode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDSECTIONCODE() {
        return bidsectioncode;
    }

    /**
     * Sets the value of the bidsectioncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDSECTIONCODE(String value) {
        this.bidsectioncode = value;
    }

    /**
     * Gets the value of the unifieddealcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNIFIEDDEALCODE() {
        return unifieddealcode;
    }

    /**
     * Sets the value of the unifieddealcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNIFIEDDEALCODE(String value) {
        this.unifieddealcode = value;
    }

    /**
     * Gets the value of the bidqualification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDQUALIFICATION() {
        return bidqualification;
    }

    /**
     * Sets the value of the bidqualification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDQUALIFICATION(String value) {
        this.bidqualification = value;
    }

    /**
     * Gets the value of the biddername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDDERNAME() {
        return biddername;
    }

    /**
     * Sets the value of the biddername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDDERNAME(String value) {
        this.biddername = value;
    }

    /**
     * Gets the value of the biddercodetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDDERCODETYPE() {
        return biddercodetype;
    }

    /**
     * Sets the value of the biddercodetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDDERCODETYPE(String value) {
        this.biddercodetype = value;
    }

    /**
     * Gets the value of the biddercode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDDERCODE() {
        return biddercode;
    }

    /**
     * Sets the value of the biddercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDDERCODE(String value) {
        this.biddercode = value;
    }

    /**
     * Gets the value of the bidderrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDDERROLE() {
        return bidderrole;
    }

    /**
     * Sets the value of the bidderrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDDERROLE(String value) {
        this.bidderrole = value;
    }

    /**
     * Gets the value of the tenderdocgettime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERDOCGETTIME() {
        return tenderdocgettime;
    }

    /**
     * Sets the value of the tenderdocgettime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERDOCGETTIME(String value) {
        this.tenderdocgettime = value;
    }

    /**
     * Gets the value of the tenderdocgetmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENDERDOCGETMETHOD() {
        return tenderdocgetmethod;
    }

    /**
     * Sets the value of the tenderdocgetmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENDERDOCGETMETHOD(String value) {
        this.tenderdocgetmethod = value;
    }

    /**
     * Gets the value of the biddocreferendtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDDOCREFERENDTIME() {
        return biddocreferendtime;
    }

    /**
     * Sets the value of the biddocreferendtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDDOCREFERENDTIME(String value) {
        this.biddocreferendtime = value;
    }

    /**
     * Gets the value of the biddocrefermethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDDOCREFERMETHOD() {
        return biddocrefermethod;
    }

    /**
     * Sets the value of the biddocrefermethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDDOCREFERMETHOD(String value) {
        this.biddocrefermethod = value;
    }

    /**
     * Gets the value of the bidinviteendtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDINVITEENDTIME() {
        return bidinviteendtime;
    }

    /**
     * Sets the value of the bidinviteendtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDINVITEENDTIME(String value) {
        this.bidinviteendtime = value;
    }

    /**
     * Gets the value of the bidinviteissuetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIDINVITEISSUETIME() {
        return bidinviteissuetime;
    }

    /**
     * Sets the value of the bidinviteissuetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIDINVITEISSUETIME(String value) {
        this.bidinviteissuetime = value;
    }

    /**
     * Gets the value of the platformcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLATFORMCODE() {
        return platformcode;
    }

    /**
     * Sets the value of the platformcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLATFORMCODE(String value) {
        this.platformcode = value;
    }

    /**
     * Gets the value of the pubserviceplatcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUBSERVICEPLATCODE() {
        return pubserviceplatcode;
    }

    /**
     * Sets the value of the pubserviceplatcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUBSERVICEPLATCODE(String value) {
        this.pubserviceplatcode = value;
    }

    /**
     * Gets the value of the datatimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATATIMESTAMP() {
        return datatimestamp;
    }

    /**
     * Sets the value of the datatimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATATIMESTAMP(String value) {
        this.datatimestamp = value;
    }

}
