package com.sxca.pspde.webservice.server;

import com.itender.ms.platform.Config;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-27T11:06:05.852+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "PspdeFileWSService", 
                  wsdlLocation = Config.shanxiDomain+"/pspde/services/pspdefilews?wsdl",
                  targetNamespace = "http://server.webservice.pspde.sxca.com/") 
public class PspdeFileWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.webservice.pspde.sxca.com/", "PspdeFileWSService");
    public final static QName PspdeFileWSPort = new QName("http://server.webservice.pspde.sxca.com/", "PspdeFileWSPort");
    static {
        URL url = null;
        try {
            url = new URL(Config.shanxiDomain+"/pspde/services/pspdefilews?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PspdeFileWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", Config.shanxiDomain+"/pspde/services/pspdefilews?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PspdeFileWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PspdeFileWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PspdeFileWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PspdeFileWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PspdeFileWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PspdeFileWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PspdeFileWS
     */
    @WebEndpoint(name = "PspdeFileWSPort")
    public PspdeFileWS getPspdeFileWSPort() {
        return super.getPort(PspdeFileWSPort, PspdeFileWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PspdeFileWS
     */
    @WebEndpoint(name = "PspdeFileWSPort")
    public PspdeFileWS getPspdeFileWSPort(WebServiceFeature... features) {
        return super.getPort(PspdeFileWSPort, PspdeFileWS.class, features);
    }

}
