
package com.sxca.pspde.webservice.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PspdeWS", targetNamespace = "http://server.webservice.pspde.sxca.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PspdeWS {
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExtractResultInform", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.GetExtractResultInform")
    @ResponseWrapper(localName = "getExtractResultInformResponse", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.GetExtractResultInformResponse")
    public String getExtractResultInform(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sxca.pspde.webservice.server.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extract", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.Extract")
    @ResponseWrapper(localName = "extractResponse", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.ExtractResponse")
    public Result extract(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3);

    /**
     *
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @param arg8
     * @return
     *     returns com.sxca.pspde.webservice.server.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receiveInfo", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.ReceiveInfo")
    @ResponseWrapper(localName = "receiveInfoResponse", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.ReceiveInfoResponse")
    public Result receiveInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    String arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    String arg6,
            @WebParam(name = "arg7", targetNamespace = "")
                    String arg7,
            @WebParam(name = "arg8", targetNamespace = "")
                    String arg8);

    /**
     *
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receiveInfoUnionCode", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.ReceiveInfoUnionCode")
    @ResponseWrapper(localName = "receiveInfoUnionCodeResponse", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.ReceiveInfoUnionCodeResponse")
    public String receiveInfoUnionCode(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3);

    /**
     *
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sxca.pspde.webservice.server.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "expertApply", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.ExpertApply")
    @ResponseWrapper(localName = "expertApplyResponse", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.ExpertApplyResponse")
    public Result expertApply(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4);

    /**
     *
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sxca.pspde.webservice.server.ExtractResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExtractResult", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.GetExtractResult")
    @ResponseWrapper(localName = "getExtractResultResponse", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.GetExtractResultResponse")
    public ExtractResult getExtractResult(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3);

    /**
     *
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sxca.pspde.webservice.server.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "expertSpecialtyEdit", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.ExpertSpecialtyEdit")
    @ResponseWrapper(localName = "expertSpecialtyEditResponse", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.ExpertSpecialtyEditResponse")
    public Result expertSpecialtyEdit(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3);

    /**
     *
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sxca.pspde.webservice.server.ExpertApplyStatusResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExpertApplyStatus", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.GetExpertApplyStatus")
    @ResponseWrapper(localName = "getExpertApplyStatusResponse", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.GetExpertApplyStatusResponse")
    public ExpertApplyStatusResult getExpertApplyStatus(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3);


    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUnitList", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.FindUnitList")
    @ResponseWrapper(localName = "findUnitListResponse", targetNamespace = "http://server.webservice.pspde.sxca.com/", className = "com.sxca.pspde.webservice.server.FindUnitListResponse")
    public List<String> findUnitList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);



}
