
package com.itender.ms.platform.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-27T11:06:05.768+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class PspdeFileWS_PspdeFileWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.webservice.pspde.sxca.com/", "PspdeFileWSService");

    private PspdeFileWS_PspdeFileWSPort_Client() {
    }

    public static void main(String args[]) throws Exception {
//        URL wsdlURL = PspdeFileWSService.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        PspdeFileWSService ss = new PspdeFileWSService(wsdlURL, SERVICE_NAME);
//        PspdeFileWS port = ss.getPspdeFileWSPort();  
//        
//        {
//        System.out.println("Invoking saveAttachments...");
////        com.sxca.pspde.webservice.server.AttachmentsWS _saveAttachments_arg0 = null;
//        
//        AttachmentsWS attachment = new AttachmentsWS();
////        attachment.setAttachmentCount(1);
//        attachment.setPlatId("096ad70d-2fd4-495c-afd1-e2305a8160e4");
//        attachment.setRelateId("096ad70d-2fd4-495c-afd1-e2305a8160e4");
//        attachment.setUserId(APP.getPlatformUserId());
//        attachment.setSerialNumber(value);
//        attachment.setBusinessType("3");
//        attachment.setKey(APP.getAppKey());
//        attachment.setMd5(value);
//        attachment.setAttachmentFileName("招标公告附件");
//        attachment.setAttachmentName("招标公告附件");
//        attachment.setAttachmentSetCode("TENDER_NOTICE");
//        attachment.setAttachmentType("doc");
//        attachment.setUrl("http://221.204.13.97/attachment/download/66ce84a5-9f4b-4423-ba1c-a69b80faf3bc");
//        
//        com.sxca.pspde.webservice.server.Result _saveAttachments__return = port.saveAttachments(attachment);
//        System.out.println("saveAttachments.result=" + _saveAttachments__return);
//
//
//        }

        System.exit(0);
    }

}
